# This file was generated by GoReleaser. DO NOT EDIT.
cask "up" do
  name "up"
  desc "UP (Unified Properties) CLI tool - parse, format, validate, and work with UP documents"
  homepage "https://github.com/uplang/tools"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "up"

  on_macos do
    on_intel do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_darwin_amd64.tar.gz"
      sha256 "23eaea4df4b1f4890f6953285e91a9a911f4a9d9d195b2f9a09e8a4c4db7c790"
    end
    on_arm do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_darwin_arm64.tar.gz"
      sha256 "20fe8cff9585edb9399734fc06f3f2297696df0a62e889b4f78f8e80d246a5ae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_linux_amd64.tar.gz"
      sha256 "e94f60e3d94d64dc5c70f05d4655d5deabcd5b2fcd3c21cd156f95676d88e3f0"
    end
    on_arm do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_linux_arm64.tar.gz"
      sha256 "4b252c2a80b706e5060e00862f9210216cfff5d202e7a60d440c099d2611bdc9"
    end
  end

  caveats do
    "UP CLI has been installed!"
    ""
    "Documentation: https://github.com/uplang/tools/tree/main/up"
    ""
    "Common commands:"
    "  up parse -i config.up --pretty"
    "  up format -i config.up"
    "  up validate -i config.up"
  end

  # No zap stanza required
end
