# This file was generated by GoReleaser. DO NOT EDIT.
cask "up" do
  name "up"
  desc "UP (Unified Properties) CLI tool - parse, format, validate, and work with UP documents"
  homepage "https://github.com/uplang/tools"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "up"

  on_macos do
    on_intel do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_darwin_amd64.tar.gz"
      sha256 "ab78e6fae3cf1b414f00f352ebd3235ed8d749f6679b0850e85822df90811b21"
    end
    on_arm do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_darwin_arm64.tar.gz"
      sha256 "931a20275d40b1c3d1b17d6ffb1a65b4f86e2e58a8ce8d48cd102d3a368c3ee8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_linux_amd64.tar.gz"
      sha256 "a3e8dc92c468a42c1d6a63d5c469c5a1c2725ceaed6ae3156e4e6a1547bf1eb0"
    end
    on_arm do
      url "https://github.com/uplang/tools/releases/download/v#{version}/up_#{version}_linux_arm64.tar.gz"
      sha256 "2e9e45a81565a399e5b5ffe47c15fa9887abb1b8fddd76d8936ff94e658c048c"
    end
  end

  caveats do
    "UP CLI has been installed!"
    ""
    "Documentation: https://github.com/uplang/tools/tree/main/up"
    ""
    "Common commands:"
    "  up parse -i config.up --pretty"
    "  up format -i config.up"
    "  up validate -i config.up"
  end

  # No zap stanza required
end
