# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpExamples < Formula
  desc "UP (Unified Properties) examples test runner"
  homepage "https://github.com/uplang/tools"
  version "0.0.13"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-examples_0.0.13_darwin_amd64.tar.gz"
      sha256 "62c04571e56b84cf235b37567c33cf84605448dcc0878c20cdfee44fd19ac86e"

      def install
        bin.install "examples"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-examples_0.0.13_darwin_arm64.tar.gz"
      sha256 "9695cdb8d3632576900daeddabd5e4329deca122fe5818e7612be6452a99a0e9"

      def install
        bin.install "examples"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-examples_0.0.13_linux_amd64.tar.gz"
      sha256 "c7c96c18d5551c213a77cf77c949571002204c9235bbaa0b99bca312cbdb11ed"
      def install
        bin.install "examples"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-examples_0.0.13_linux_arm64.tar.gz"
      sha256 "eb9044579ff9aaef72b56879397a69f600c8441c89cf92924f92140960266306"
      def install
        bin.install "examples"
      end
    end
  end
end
