# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpExamples < Formula
  desc "UP (Unified Properties) examples test runner"
  homepage "https://github.com/uplang/tools"
  version "0.0.12"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up-examples_0.0.12_darwin_amd64.tar.gz"
      sha256 "dd04e0d568f6fa3b1a69f17547f8e6558ec7ca51cf29e91fd437c2705853e7d6"

      def install
        bin.install "examples"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up-examples_0.0.12_darwin_arm64.tar.gz"
      sha256 "8d20ea26e66a03965ddc6282cef383688243cb74be88e93fde7b535b7efebe96"

      def install
        bin.install "examples"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up-examples_0.0.12_linux_amd64.tar.gz"
      sha256 "9f6c99c0bb1801a5889985feeda14d4aaf21b24a01ac91b65b9524af66fa6b64"
      def install
        bin.install "examples"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up-examples_0.0.12_linux_arm64.tar.gz"
      sha256 "82628be544a4bbc17800d6a90a88be29b5cbafc016b02420ae6efcac623fc0bd"
      def install
        bin.install "examples"
      end
    end
  end
end
