# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpLanguageServer < Formula
  desc "Language Server Protocol implementation for UP"
  homepage "https://github.com/uplang/tools"
  version "0.0.13"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-language-server_0.0.13_darwin_amd64.tar.gz"
      sha256 "cabf131980f60fbdd8b3e96eeb0af4fd1262487d926d0fb46bb962e49a356116"

      def install
        bin.install "up-language-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-language-server_0.0.13_darwin_arm64.tar.gz"
      sha256 "3b5171945ea9a484397275a5cac88d7a2cbe5bcbe3e826701bbf5d794b2b4d87"

      def install
        bin.install "up-language-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-language-server_0.0.13_linux_amd64.tar.gz"
      sha256 "9d26c4c334a9814d2633f3a39e018be30ce545e0a928b79b3078581a5ad96ec8"
      def install
        bin.install "up-language-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-language-server_0.0.13_linux_arm64.tar.gz"
      sha256 "0913fbee0cb0ccfb2b6f17e01c3fa6c7538cc108f354a842c168f64c59521fd5"
      def install
        bin.install "up-language-server"
      end
    end
  end
end
