# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsTime < Formula
  desc "UP namespace plugin for time manipulation and formatting"
  homepage "https://github.com/uplang/ns"
  version "0.0.9"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-time_0.0.9_darwin_amd64.tar.gz"
      sha256 "81b3300d161f6e9a2141d0838d606e5cb0bbebb8abce06f26c177cef7c75f702"

      def install
        bin.install "up-ns-time"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-time_0.0.9_darwin_arm64.tar.gz"
      sha256 "acf1d65a7a2673c979cab888b989a61b0f9360bc2e4b67fe76afc943c6dd79f5"

      def install
        bin.install "up-ns-time"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-time_0.0.9_linux_amd64.tar.gz"
      sha256 "c1ea0a3b7c81964e64480612d23a8f462ef185f5ecf3b4243f0dc7348afd9688"
      def install
        bin.install "up-ns-time"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-time_0.0.9_linux_arm64.tar.gz"
      sha256 "a7f3ad9a534b6e0e72cb47e3bbf44b4b927363635a4567d4ff3bc02a0e5358b9"
      def install
        bin.install "up-ns-time"
      end
    end
  end
end
