# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsMath < Formula
  desc "UP namespace plugin for mathematical operations"
  homepage "https://github.com/uplang/ns"
  version "0.0.6"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-math_0.0.6_darwin_amd64.tar.gz"
      sha256 "34fbb3c74c89884d1fc0a7ebdeb4672f9fb234416320fe505934c197e622b498"

      def install
        bin.install "up-ns-math"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-math_0.0.6_darwin_arm64.tar.gz"
      sha256 "86f7fb67cccd193b0f42d2bb6673aaf2ac6317a0dec871c674b5be84d06182cc"

      def install
        bin.install "up-ns-math"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-math_0.0.6_linux_amd64.tar.gz"
      sha256 "6198d3faac74462fab663b57298c2518d0920d19480fd25769f6d1097551cb92"
      def install
        bin.install "up-ns-math"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-math_0.0.6_linux_arm64.tar.gz"
      sha256 "21b5941d81694b00ddf20ccc71b543df2017022bbd61ae38da4cd0ace1049186"
      def install
        bin.install "up-ns-math"
      end
    end
  end
end
