# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsFile < Formula
  desc "UP namespace plugin for file system operations"
  homepage "https://github.com/uplang/ns"
  version "0.0.5"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-file_0.0.5_darwin_amd64.tar.gz"
      sha256 "abbcd8725b036a03b7f8f0661d15d183cec05105143e0a7b035a044a5af95820"

      def install
        bin.install "up-ns-file"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-file_0.0.5_darwin_arm64.tar.gz"
      sha256 "ebff90572526f1ecbd8c14a57084c22f7b66e65cc0d45efbafa8e0e594ca7c39"

      def install
        bin.install "up-ns-file"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-file_0.0.5_linux_amd64.tar.gz"
      sha256 "b9eaeafe77968693a416aeb2a6fda75ba448c4a0e502dc9092a577f38fe50415"
      def install
        bin.install "up-ns-file"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-file_0.0.5_linux_arm64.tar.gz"
      sha256 "b574d8c746ffb1c978d025c6aa2343b331db5528177fa81d325c98c9bb562f2c"
      def install
        bin.install "up-ns-file"
      end
    end
  end
end
