# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsId < Formula
  desc "UP namespace plugin for ID generation (UUID, ULID, etc.)"
  homepage "https://github.com/uplang/ns"
  version "0.0.5"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-id_0.0.5_darwin_amd64.tar.gz"
      sha256 "9fe8d1a73149090eb384349c0ca53b48527dd86e74c50131825fd9097798a581"

      def install
        bin.install "up-ns-id"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-id_0.0.5_darwin_arm64.tar.gz"
      sha256 "e309773fc5bf0db26763d4845b383759b4cee4ecfe2c019daa83ec1f27b86a7c"

      def install
        bin.install "up-ns-id"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-id_0.0.5_linux_amd64.tar.gz"
      sha256 "f5c3396901732b630eb57598bae82b5005dc791a4dc84c1b6707f9d2d8ee8668"
      def install
        bin.install "up-ns-id"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-id_0.0.5_linux_arm64.tar.gz"
      sha256 "4b4f3d7296a60fdd45527ca06fc6af11f178e357382c3ca23b92dde1ea1b816b"
      def install
        bin.install "up-ns-id"
      end
    end
  end
end
