# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsFile < Formula
  desc "UP namespace plugin for file system operations"
  homepage "https://github.com/uplang/ns"
  version "0.0.9"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-file_0.0.9_darwin_amd64.tar.gz"
      sha256 "68c17da1a5ec2e83f2b8ef65b4e0a901b8519e18763aaae88ce7b8a6bcaa3d3a"

      def install
        bin.install "up-ns-file"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-file_0.0.9_darwin_arm64.tar.gz"
      sha256 "46140a8752bb952ce644214de633f08749c78a1ff8e2c8abc76f98fc74d1d645"

      def install
        bin.install "up-ns-file"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-file_0.0.9_linux_amd64.tar.gz"
      sha256 "00a5f3d8b762b2332d76838962c5579015ded05df8d6b294d12cd5e31089ccd6"
      def install
        bin.install "up-ns-file"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-file_0.0.9_linux_arm64.tar.gz"
      sha256 "e3d786c4533853368a3b16b8132d76915c88f7802850cab1e40dcfda1a1a0c9e"
      def install
        bin.install "up-ns-file"
      end
    end
  end
end
