# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsFake < Formula
  desc "UP namespace plugin for fake data generation"
  homepage "https://github.com/uplang/ns"
  version "0.0.9"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-fake_0.0.9_darwin_amd64.tar.gz"
      sha256 "b01f85e6218fceac62e2efffc9662a3898f93f24ef31d7fa56db7d5dad5faee3"

      def install
        bin.install "up-ns-fake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-fake_0.0.9_darwin_arm64.tar.gz"
      sha256 "e2e55425237252cd3f8ae02794f7d5abd96cf9d5deeea1384676fd2ef15374ba"

      def install
        bin.install "up-ns-fake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-fake_0.0.9_linux_amd64.tar.gz"
      sha256 "7dd788fa0b681daefbbff368b5c471355c1af5a067592988c06fca90487d58ba"
      def install
        bin.install "up-ns-fake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-fake_0.0.9_linux_arm64.tar.gz"
      sha256 "1ffc035cd4588bb6500c629c5d167d8a4a638e89e75c8fca0183761033db90bf"
      def install
        bin.install "up-ns-fake"
      end
    end
  end
end
