# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsList < Formula
  desc "UP namespace plugin for list generation and manipulation"
  homepage "https://github.com/uplang/ns"
  version "0.0.9"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-list_0.0.9_darwin_amd64.tar.gz"
      sha256 "cd12e6f0db33b86176f9a299841840845aca9be8f9a938d14bc8b1ffb637981d"

      def install
        bin.install "up-ns-list"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-list_0.0.9_darwin_arm64.tar.gz"
      sha256 "e612cba68455ad53cbb3fb64c52f611ab8bf46df2e8b34bf05f4a9039312af98"

      def install
        bin.install "up-ns-list"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-list_0.0.9_linux_amd64.tar.gz"
      sha256 "bb2ef34f10b71d1f253d4bae391737977623b19238d1f7431c3a6c394782f358"
      def install
        bin.install "up-ns-list"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-list_0.0.9_linux_arm64.tar.gz"
      sha256 "cb41ce10dd2c7f7702222a66232c6ab2d743f34abb820198c003f760bfced492"
      def install
        bin.install "up-ns-list"
      end
    end
  end
end
