# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsRandom < Formula
  desc "UP namespace plugin for random value generation"
  homepage "https://github.com/uplang/ns"
  version "0.0.6"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-random_0.0.6_darwin_amd64.tar.gz"
      sha256 "f4197017258dcb6f543309f37957490aceb6c90d1d55c0c8178e345241bf15a6"

      def install
        bin.install "up-ns-random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-random_0.0.6_darwin_arm64.tar.gz"
      sha256 "87215c6ed70cf76fd0c6d5e37aebcc3a74cf45efbf96dbeb6700c281ce872f09"

      def install
        bin.install "up-ns-random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-random_0.0.6_linux_amd64.tar.gz"
      sha256 "0ac80f679a8f6901099156e58447ae595da72e6bbb9b572221ca419b2f970631"
      def install
        bin.install "up-ns-random"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-random_0.0.6_linux_arm64.tar.gz"
      sha256 "8ee3dedece384883272b228628911090799488e6aab2895741313836021963f7"
      def install
        bin.install "up-ns-random"
      end
    end
  end
end
