# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsList < Formula
  desc "UP namespace plugin for list generation and manipulation"
  homepage "https://github.com/uplang/ns"
  version "0.0.4"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.4/up-ns-list_0.0.4_darwin_amd64.tar.gz"
      sha256 "24ab94e5ad98e95bad1dea75352069bf33d953de18e7a1f02eedc9ddda53dfac"

      def install
        bin.install "up-ns-list"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.4/up-ns-list_0.0.4_darwin_arm64.tar.gz"
      sha256 "f868889b8b3e49ae0be97aadc503e32a973a475d7f9211c3cb2c8ceef46ca78d"

      def install
        bin.install "up-ns-list"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.4/up-ns-list_0.0.4_linux_amd64.tar.gz"
      sha256 "6ea85735181086199767f48c5ca97fb6c8d0c628ddff3fc7f15560fc5fd5754e"
      def install
        bin.install "up-ns-list"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.4/up-ns-list_0.0.4_linux_arm64.tar.gz"
      sha256 "92e222fd8bdff6e97b38ba5a66df212d5cfa2b78f8f13bdcb61af9aaf33644e1"
      def install
        bin.install "up-ns-list"
      end
    end
  end
end
