# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsString < Formula
  desc "UP namespace plugin for string manipulation"
  homepage "https://github.com/uplang/ns"
  version "0.0.5"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-string_0.0.5_darwin_amd64.tar.gz"
      sha256 "b643868950bb1905cfa63e23543249e0ab389360d685a52c1f3b78552f932993"

      def install
        bin.install "up-ns-string"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-string_0.0.5_darwin_arm64.tar.gz"
      sha256 "806d6d6fc79cf3789b10635bbedb2b33c2af82871d0a0686bf93f824910aa8c9"

      def install
        bin.install "up-ns-string"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-string_0.0.5_linux_amd64.tar.gz"
      sha256 "4b0abc8ead6f80628675808e389033f07f3691a672933356295e49f70bba3ef7"
      def install
        bin.install "up-ns-string"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-string_0.0.5_linux_arm64.tar.gz"
      sha256 "e7ecf32b15ccaa4ed1d5a55d1219a394d1472385c256b3f8d75ac70b066f66dc"
      def install
        bin.install "up-ns-string"
      end
    end
  end
end
