# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsList < Formula
  desc "UP namespace plugin for list generation and manipulation"
  homepage "https://github.com/uplang/ns"
  version "0.0.5"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-list_0.0.5_darwin_amd64.tar.gz"
      sha256 "90d2427612e586ce342553a1285a387e0cb97afe3c8be45f757aff4e7de17ea8"

      def install
        bin.install "up-ns-list"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-list_0.0.5_darwin_arm64.tar.gz"
      sha256 "e8042169d9afa05e70f08f346e575bf76bc04ac42be51229bbd45c13bca4a56c"

      def install
        bin.install "up-ns-list"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-list_0.0.5_linux_amd64.tar.gz"
      sha256 "09d8b6c59f4e80535e469ebf12ee5bfbce092b6ffc70948eab29e18070241592"
      def install
        bin.install "up-ns-list"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-list_0.0.5_linux_arm64.tar.gz"
      sha256 "cf9ac2e29fa1ee91c7ae5bdf5374a957ead29da43dc22995056f0f3ecb9ea190"
      def install
        bin.install "up-ns-list"
      end
    end
  end
end
