# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsRandom < Formula
  desc "UP namespace plugin for random value generation"
  homepage "https://github.com/uplang/ns"
  version "0.0.9"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-random_0.0.9_darwin_amd64.tar.gz"
      sha256 "022e6f1453212d09b3953de0ba4f825f7148d93ba2ae43355f80a7fd7a4fe561"

      def install
        bin.install "up-ns-random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-random_0.0.9_darwin_arm64.tar.gz"
      sha256 "56742157ed469221f8fe48c9c92bb86b98d5621c081dc27df0045dc66043757c"

      def install
        bin.install "up-ns-random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-random_0.0.9_linux_amd64.tar.gz"
      sha256 "9558c777bd83a4d22ddf77b6a8c3613b21404a1066f7488b2dcca0e3815c5b16"
      def install
        bin.install "up-ns-random"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-random_0.0.9_linux_arm64.tar.gz"
      sha256 "d20eb66e06c8a038361ef8517d31004e2a34f512bf8b4d6a1886da458e88537b"
      def install
        bin.install "up-ns-random"
      end
    end
  end
end
