# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsFake < Formula
  desc "UP namespace plugin for fake data generation"
  homepage "https://github.com/uplang/ns"
  version "0.0.6"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-fake_0.0.6_darwin_amd64.tar.gz"
      sha256 "6ae9e035271238f60881b1a1f1e83240a893a5a241859ea9f310738f44ac285d"

      def install
        bin.install "up-ns-fake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-fake_0.0.6_darwin_arm64.tar.gz"
      sha256 "3647935537895441ffa3fdf1110794999859caded20549f3afd8b42856d18fac"

      def install
        bin.install "up-ns-fake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-fake_0.0.6_linux_amd64.tar.gz"
      sha256 "7f4900b30634b886fa285e321334a0c79c26894d620c71e521351c9cb99db9b4"
      def install
        bin.install "up-ns-fake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.6/up-ns-fake_0.0.6_linux_arm64.tar.gz"
      sha256 "3e7b765430d0581113cc6dae0c80af83872cc2a528b0366661769d9959f394f9"
      def install
        bin.install "up-ns-fake"
      end
    end
  end
end
