# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsRandom < Formula
  desc "UP namespace plugin for random value generation"
  homepage "https://github.com/uplang/ns"
  version "0.0.7"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-random_0.0.7_darwin_amd64.tar.gz"
      sha256 "d1e8437c8806f96cf554a54972cd98cfd7ac38c6c984437735151ea6999ea957"

      def install
        bin.install "up-ns-random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-random_0.0.7_darwin_arm64.tar.gz"
      sha256 "7b3032859a8f516a91ad2a84093252951419e4d432d00232a3aa5a606fa5a4ab"

      def install
        bin.install "up-ns-random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-random_0.0.7_linux_amd64.tar.gz"
      sha256 "b09e01d0d2ce7a070ccbe6b9a5298bfd88cd80c556560d0a730ce4ec4cd346ac"
      def install
        bin.install "up-ns-random"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-random_0.0.7_linux_arm64.tar.gz"
      sha256 "6e49d1cac4e37388eee29564532be151984be250db8cec05e60694feca309eda"
      def install
        bin.install "up-ns-random"
      end
    end
  end
end
