# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsString < Formula
  desc "UP namespace plugin for string manipulation"
  homepage "https://github.com/uplang/ns"
  version "0.0.7"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-string_0.0.7_darwin_amd64.tar.gz"
      sha256 "3206f507e10134bc7dd3b8e93364d4403b136a0b9c307bde29d2d9017df653ff"

      def install
        bin.install "up-ns-string"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-string_0.0.7_darwin_arm64.tar.gz"
      sha256 "0edd5977565a723df44e032112156ec246b431ee452c4fb40f8b9ef6f6a28916"

      def install
        bin.install "up-ns-string"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-string_0.0.7_linux_amd64.tar.gz"
      sha256 "af7ebe272b7129c0eaf84e7301057c4a92b6f83b0337e0b0852b2a007e868f3f"
      def install
        bin.install "up-ns-string"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-string_0.0.7_linux_arm64.tar.gz"
      sha256 "0a17d5845cce40371dd6cf4c6468a3be8dcd953b86770ba84dd151608d0bfbfe"
      def install
        bin.install "up-ns-string"
      end
    end
  end
end
