# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsTime < Formula
  desc "UP namespace plugin for time manipulation and formatting"
  homepage "https://github.com/uplang/ns"
  version "0.0.5"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-time_0.0.5_darwin_amd64.tar.gz"
      sha256 "cfd1c4dec850d96105bb6ad3a90be2bca31505918576cc0ae93895f2e3b04de1"

      def install
        bin.install "up-ns-time"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-time_0.0.5_darwin_arm64.tar.gz"
      sha256 "cad1c1de8e35e41da2c4ab08c74dc555807f68a85d4ab8e94aceb77e78ce1343"

      def install
        bin.install "up-ns-time"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-time_0.0.5_linux_amd64.tar.gz"
      sha256 "728877e5096e866b845a36b9345cb2ce7117f5bd27d607c1f231b87460d6abfb"
      def install
        bin.install "up-ns-time"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.5/up-ns-time_0.0.5_linux_arm64.tar.gz"
      sha256 "6c9b6888d82698937f592c0f6b80804181c361b9d7cd38d5cd0bf14980584cbf"
      def install
        bin.install "up-ns-time"
      end
    end
  end
end
