# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsId < Formula
  desc "UP namespace plugin for ID generation (UUID, ULID, etc.)"
  homepage "https://github.com/uplang/ns"
  version "0.0.7"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-id_0.0.7_darwin_amd64.tar.gz"
      sha256 "ffc7e8aed6ceb63936b8172b6fedebacce47e2f87e30ddd1d38dde8204cced5f"

      def install
        bin.install "up-ns-id"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-id_0.0.7_darwin_arm64.tar.gz"
      sha256 "806e6dee4c6430f772dc2fd50f8aa87386eb2db9bacc706220d1bd2a65ccb25c"

      def install
        bin.install "up-ns-id"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-id_0.0.7_linux_amd64.tar.gz"
      sha256 "9ec256733baab2ca662230b9a03b69d6db27ea2f289809bb64f035e61b762fca"
      def install
        bin.install "up-ns-id"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.7/up-ns-id_0.0.7_linux_arm64.tar.gz"
      sha256 "5735700ce97740b44d3a49d20692b1839f431022d8e8161aca85dee98011b0a0"
      def install
        bin.install "up-ns-id"
      end
    end
  end
end
