# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpNsEnv < Formula
  desc "UP namespace plugin for environment variable access"
  homepage "https://github.com/uplang/ns"
  version "0.0.9"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-env_0.0.9_darwin_amd64.tar.gz"
      sha256 "0e822cbdcfbbd57f4580d4ddf7482dc00a41575b0e27d109f01e32187397372f"

      def install
        bin.install "up-ns-env"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-env_0.0.9_darwin_arm64.tar.gz"
      sha256 "87a7dd847c9c585562020a3c2e1ba84c4dfb3aeb7cd33be12bc3cbd0d8e17979"

      def install
        bin.install "up-ns-env"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-env_0.0.9_linux_amd64.tar.gz"
      sha256 "3ee295601114a1399d7835ae2d01590f1d6863a3f16b9165131aabd0de594f37"
      def install
        bin.install "up-ns-env"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/ns/releases/download/v0.0.9/up-ns-env_0.0.9_linux_arm64.tar.gz"
      sha256 "bd192675d96e266f6cba5950672c501724319b60ea15fc96d505d833458286ef"
      def install
        bin.install "up-ns-env"
      end
    end
  end
end
