# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpRepl < Formula
  desc "Interactive REPL for UP (Unified Properties)"
  homepage "https://github.com/uplang/tools"
  version "0.0.13"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-repl_0.0.13_darwin_amd64.tar.gz"
      sha256 "70729f48e1764a6f663f426324ab8d4ddd4122898fbe3f100fa452e71e8ec6f6"

      def install
        bin.install "up-repl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-repl_0.0.13_darwin_arm64.tar.gz"
      sha256 "a2ff0ae4c60ab483fc1ba19fd799e8df4a1fb0373460689c50f4ef06a5de1eee"

      def install
        bin.install "up-repl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-repl_0.0.13_linux_amd64.tar.gz"
      sha256 "3ba004e1b21e7f9046ab21060375b6f302ff830e70677ae63890da81efce5252"
      def install
        bin.install "up-repl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.13/up-repl_0.0.13_linux_arm64.tar.gz"
      sha256 "f723eb520463cb49bd61b2218f5c8410758d39f9b5d80a8d54651512f3e9ff43"
      def install
        bin.install "up-repl"
      end
    end
  end
end
