# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Up < Formula
  desc "UP (Unified Properties) CLI tool - parse, format, validate, and work with UP documents"
  homepage "https://github.com/uplang/tools"
  version "0.0.1"
  license "GPL-3.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/tools/releases/download/v0.0.1/up_0.0.1_darwin_amd64.tar.gz"
      sha256 "4febc4c812f17b9b95c2b5e8bc68d21d7801ce8e36636be70e4c3b9900efa2d0"

      def install
        bin.install "up"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/tools/releases/download/v0.0.1/up_0.0.1_darwin_arm64.tar.gz"
      sha256 "c18586b7548603449d56303d86d6c1e1ccfdc20181a2d0e272dd9493ad47413d"

      def install
        bin.install "up"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.1/up_0.0.1_linux_amd64.tar.gz"
      sha256 "916e9b3c9b53ea273a91fa720e6aceb48245d4b20496f64749c4410aa5bcbe19"
      def install
        bin.install "up"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.1/up_0.0.1_linux_arm64.tar.gz"
      sha256 "a92021675e12c0b5bc35c8ed52673ecb88e2cb542261c0b227566cc38f852125"
      def install
        bin.install "up"
      end
    end
  end

  def caveats
    <<~EOS
      UP CLI has been installed!

      Documentation: https://github.com/uplang/tools/tree/main/up

      Common commands:
        up parse -i config.up --pretty
        up format -i config.up
        up validate -i config.up
    EOS
  end

  test do
    system "#{bin}/up", "version"
    system "#{bin}/up", "parse", "--help"
  end
end
