# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Up < Formula
  desc "UP (Unified Properties) CLI tool - parse, format, validate, and work with UP documents"
  homepage "https://github.com/uplang/tools"
  version "0.0.12"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up_0.0.12_darwin_amd64.tar.gz"
      sha256 "aaac66aa0571bd111533e3620fe783f9e8e37eff4cde517ea6753c0758e93b1a"

      def install
        bin.install "up"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up_0.0.12_darwin_arm64.tar.gz"
      sha256 "68ab10772273b7c33d4b083040b69132e2b695f258fb46af518bdc7ef32b40ef"

      def install
        bin.install "up"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up_0.0.12_linux_amd64.tar.gz"
      sha256 "f40116981e3bd3c6cf21d0616b570ef13dfc472c729e12beeb1b8862ce3a11d9"
      def install
        bin.install "up"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.12/up_0.0.12_linux_arm64.tar.gz"
      sha256 "401bcfab09a8e02cbf02c4181e98b5c6dc97cf0a232a7ce71a97dd8ef9b6e292"
      def install
        bin.install "up"
      end
    end
  end

  def caveats
    <<~EOS
      UP CLI has been installed!

      Documentation: https://github.com/uplang/tools/tree/main/up

      Common commands:
        up parse -i config.up --pretty
        up format -i config.up
        up validate -i config.up
    EOS
  end
end
