# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Up < Formula
  desc "UP (Unified Properties) CLI tool - parse, format, validate, and work with UP documents"
  homepage "https://github.com/uplang/tools"
  version "0.0.7"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uplang/tools/releases/download/v0.0.7/up_0.0.7_darwin_amd64.tar.gz"
      sha256 "f72962334a8efd8a1c48d13f1d342b902b9979c51901f7a5c336059dc05de8cd"

      def install
        bin.install "up"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uplang/tools/releases/download/v0.0.7/up_0.0.7_darwin_arm64.tar.gz"
      sha256 "d7d3acd0683adaad590e8384edeb81e954d6db36ef92e23d4dbe43c81fad0e37"

      def install
        bin.install "up"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.7/up_0.0.7_linux_amd64.tar.gz"
      sha256 "6fab81cbe362be32c88f02f9414fd55aa32570bcac4139b978d097f5d7d99059"
      def install
        bin.install "up"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uplang/tools/releases/download/v0.0.7/up_0.0.7_linux_arm64.tar.gz"
      sha256 "04ecce6f1ec25673569f4a7ff589d7463e4adcb0ea73002c68d3d216917911e0"
      def install
        bin.install "up"
      end
    end
  end

  def caveats
    <<~EOS
      UP CLI has been installed!

      Documentation: https://github.com/uplang/tools/tree/main/up

      Common commands:
        up parse -i config.up --pretty
        up format -i config.up
        up validate -i config.up
    EOS
  end
end
